-- SafeStep | ERD general | PostgreSQL.
-- Documento de diseño: importar SOLO este archivo para el ERD completo.
-- No ejecutar junto con los archivos 01-06; contienen las mismas tablas.

-- SafeStep | IAM | PostgreSQL | modelo para importar a un generador ERD.
-- DDL de documentación, no migración para una base de datos con información.
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    enabled BOOLEAN NOT NULL,
    account_non_locked BOOLEAN NOT NULL,
    account_non_expired BOOLEAN NOT NULL,
    credentials_non_expired BOOLEAN NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL REFERENCES users(username),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL REFERENCES users(username),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE
);

-- SafeStep | Profiles | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email_address VARCHAR(255) NOT NULL UNIQUE,
    street_address_street VARCHAR(255),
    street_address_number VARCHAR(255),
    street_address_city VARCHAR(255),
    street_address_postal_code VARCHAR(255),
    street_address_country VARCHAR(255)
);
-- PersonName, EmailAddress y StreetAddress se embeben en profiles.
-- El enlace con users.username es lógico; no hay FK física en la entidad JPA.

-- SafeStep | Simulation | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE medical_simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    emergency_type VARCHAR(255),
    difficulty VARCHAR(255),
    duration_minutes INTEGER,
    description VARCHAR(2000),
    image_url VARCHAR(255),
    status VARCHAR(255),
    completion INTEGER,
    xp_reward INTEGER,
    coin_reward INTEGER
);

CREATE TABLE simulation_learning_goals (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    goal VARCHAR(255)
);

CREATE TABLE simulation_steps (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    external_id VARCHAR(255),
    prompt VARCHAR(1000),
    correct_option_id VARCHAR(255),
    UNIQUE (simulation_id, external_id)
);

CREATE TABLE simulation_options (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    step_external_id VARCHAR(255),
    external_id VARCHAR(255),
    label VARCHAR(1000),
    feedback VARCHAR(1000),
    FOREIGN KEY (simulation_id, step_external_id)
        REFERENCES simulation_steps(simulation_id, external_id)
);

CREATE TABLE simulation_product_suggestions (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    product_id VARCHAR(255),
    reason VARCHAR(1000)
);

CREATE TABLE simulation_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    simulation_slug VARCHAR(255) NOT NULL REFERENCES medical_simulations(slug),
    mode VARCHAR(255),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    score INTEGER,
    total_steps INTEGER,
    correct_steps INTEGER,
    time_elapsed BIGINT,
    status VARCHAR(255)
);

CREATE TABLE attempt_errors (
    attempt_id BIGINT NOT NULL REFERENCES simulation_attempts(id),
    step_number INTEGER,
    description VARCHAR(1000),
    severity VARCHAR(255)
);
-- product_id y username son referencias lógicas a otros bounded contexts.

-- SafeStep | Gamification | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    rarity VARCHAR(255),
    description VARCHAR(1000),
    unlock_requirement VARCHAR(1000)
);

CREATE TABLE missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    cadence VARCHAR(255) NOT NULL,
    goal INTEGER,
    reward_xp INTEGER,
    reward_coins INTEGER,
    status VARCHAR(255),
    instructions VARCHAR(1000),
    unlock_requirement VARCHAR(1000)
);

CREATE TABLE player_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    level INTEGER,
    xp INTEGER,
    safe_coins INTEGER,
    streak_days INTEGER,
    completed_simulations INTEGER,
    last_activity DATE
);

CREATE TABLE coin_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    simulation_id VARCHAR(255),
    simulation_title VARCHAR(255),
    base_coins INTEGER,
    earned_coins INTEGER,
    score INTEGER,
    multiplier DOUBLE PRECISION,
    accuracy DOUBLE PRECISION,
    occurred_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL,
    badge_external_id VARCHAR(255) NOT NULL REFERENCES badges(external_id),
    unlocked_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (username, badge_external_id)
);

CREATE TABLE user_mission_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL,
    mission_external_id VARCHAR(255) NOT NULL REFERENCES missions(external_id),
    progress INTEGER,
    completed BOOLEAN,
    UNIQUE (username, mission_external_id)
);
-- username y simulation_id son referencias lógicas a IAM/Simulation.

-- SafeStep | Analytics | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL,
    module_name VARCHAR(255),
    achievement_level VARCHAR(255),
    score INTEGER,
    issued_at TIMESTAMP WITH TIME ZONE,
    verification_code VARCHAR(255) NOT NULL UNIQUE,
    qr_code_url VARCHAR(255),
    downloadable_pdf_url VARCHAR(255)
);
-- AnalyticsSummary y sus métricas son agregaciones calculadas; no tabla propia.

-- SafeStep | Commerce | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    product_count INTEGER
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    category VARCHAR(255),
    type VARCHAR(255),
    image_url VARCHAR(255),
    description VARCHAR(2000),
    price NUMERIC(19, 2),
    old_price NUMERIC(19, 2),
    rating DOUBLE PRECISION,
    stock INTEGER
);

CREATE TABLE product_tags (
    product_id BIGINT NOT NULL REFERENCES products(id),
    tag VARCHAR(255)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    ordered_at DATE,
    payment_provider VARCHAR(255),
    payment_status VARCHAR(255),
    stripe_checkout_session_id VARCHAR(255),
    stripe_payment_intent_id VARCHAR(255),
    paid_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE order_items (
    order_id BIGINT NOT NULL REFERENCES orders(id),
    product_id VARCHAR(255) REFERENCES products(external_id),
    product_name VARCHAR(255),
    unit_price NUMERIC(19, 2),
    quantity INTEGER
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    product_id VARCHAR(255) NOT NULL REFERENCES products(external_id),
    quantity INTEGER,
    added_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE product_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255),
    product_id VARCHAR(255) REFERENCES products(external_id),
    reason VARCHAR(255),
    related_simulation_id VARCHAR(255),
    priority VARCHAR(255),
    dismissed BOOLEAN
);

CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255),
    discount VARCHAR(255),
    cost_coins INTEGER
);

CREATE TABLE emergency_kits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    level VARCHAR(255),
    image_url VARCHAR(255),
    description VARCHAR(2000),
    individual_price NUMERIC(19, 2),
    kit_price NUMERIC(19, 2),
    savings NUMERIC(19, 2),
    savings_percentage INTEGER,
    popular BOOLEAN
);

CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255),
    label VARCHAR(255),
    description VARCHAR(255),
    processing_fee NUMERIC(19, 2),
    available BOOLEAN
);

CREATE TABLE shipping_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255),
    label VARCHAR(255),
    recipient_name VARCHAR(255),
    phone VARCHAR(255),
    country VARCHAR(255),
    region VARCHAR(255),
    city VARCHAR(255),
    district VARCHAR(255),
    postal_code VARCHAR(255),
    street VARCHAR(255),
    street_number VARCHAR(255),
    reference VARCHAR(255),
    default_address BOOLEAN
);
-- Las columnas de usuario y otras referencias externas son lógicas.
