-- SafeStep | Profiles | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email_address VARCHAR(255) NOT NULL UNIQUE,
    street_address_street VARCHAR(255),
    street_address_number VARCHAR(255),
    street_address_city VARCHAR(255),
    street_address_postal_code VARCHAR(255),
    street_address_country VARCHAR(255)
);
-- PersonName, EmailAddress y StreetAddress se embeben en profiles.
-- El enlace con users.username es lógico; no hay FK física en la entidad JPA.
