-- SafeStep | Simulation | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE medical_simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    emergency_type VARCHAR(255),
    difficulty VARCHAR(255),
    duration_minutes INTEGER,
    description VARCHAR(2000),
    image_url VARCHAR(255),
    status VARCHAR(255),
    completion INTEGER,
    xp_reward INTEGER,
    coin_reward INTEGER
);

CREATE TABLE simulation_learning_goals (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    goal VARCHAR(255)
);

CREATE TABLE simulation_steps (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    external_id VARCHAR(255),
    prompt VARCHAR(1000),
    correct_option_id VARCHAR(255),
    UNIQUE (simulation_id, external_id)
);

CREATE TABLE simulation_options (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    step_external_id VARCHAR(255),
    external_id VARCHAR(255),
    label VARCHAR(1000),
    feedback VARCHAR(1000),
    FOREIGN KEY (simulation_id, step_external_id)
        REFERENCES simulation_steps(simulation_id, external_id)
);

CREATE TABLE simulation_product_suggestions (
    simulation_id BIGINT NOT NULL REFERENCES medical_simulations(id),
    product_id VARCHAR(255),
    reason VARCHAR(1000)
);

CREATE TABLE simulation_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    simulation_slug VARCHAR(255) NOT NULL REFERENCES medical_simulations(slug),
    mode VARCHAR(255),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    score INTEGER,
    total_steps INTEGER,
    correct_steps INTEGER,
    time_elapsed BIGINT,
    status VARCHAR(255)
);

CREATE TABLE attempt_errors (
    attempt_id BIGINT NOT NULL REFERENCES simulation_attempts(id),
    step_number INTEGER,
    description VARCHAR(1000),
    severity VARCHAR(255)
);
-- product_id y username son referencias lógicas a otros bounded contexts.
