-- SafeStep | Gamification | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    rarity VARCHAR(255),
    description VARCHAR(1000),
    unlock_requirement VARCHAR(1000)
);

CREATE TABLE missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    cadence VARCHAR(255) NOT NULL,
    goal INTEGER,
    reward_xp INTEGER,
    reward_coins INTEGER,
    status VARCHAR(255),
    instructions VARCHAR(1000),
    unlock_requirement VARCHAR(1000)
);

CREATE TABLE player_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    level INTEGER,
    xp INTEGER,
    safe_coins INTEGER,
    streak_days INTEGER,
    completed_simulations INTEGER,
    last_activity DATE
);

CREATE TABLE coin_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    simulation_id VARCHAR(255),
    simulation_title VARCHAR(255),
    base_coins INTEGER,
    earned_coins INTEGER,
    score INTEGER,
    multiplier DOUBLE PRECISION,
    accuracy DOUBLE PRECISION,
    occurred_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL,
    badge_external_id VARCHAR(255) NOT NULL REFERENCES badges(external_id),
    unlocked_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (username, badge_external_id)
);

CREATE TABLE user_mission_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL,
    mission_external_id VARCHAR(255) NOT NULL REFERENCES missions(external_id),
    progress INTEGER,
    completed BOOLEAN,
    UNIQUE (username, mission_external_id)
);
-- username y simulation_id son referencias lógicas a IAM/Simulation.
