-- SafeStep | Analytics | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL,
    module_name VARCHAR(255),
    achievement_level VARCHAR(255),
    score INTEGER,
    issued_at TIMESTAMP WITH TIME ZONE,
    verification_code VARCHAR(255) NOT NULL UNIQUE,
    qr_code_url VARCHAR(255),
    downloadable_pdf_url VARCHAR(255)
);
-- AnalyticsSummary y sus métricas son agregaciones calculadas; no tabla propia.
