-- SafeStep | Commerce | PostgreSQL | modelo para importar a un generador ERD.
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    product_count INTEGER
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    category VARCHAR(255),
    type VARCHAR(255),
    image_url VARCHAR(255),
    description VARCHAR(2000),
    price NUMERIC(19, 2),
    old_price NUMERIC(19, 2),
    rating DOUBLE PRECISION,
    stock INTEGER
);

CREATE TABLE product_tags (
    product_id BIGINT NOT NULL REFERENCES products(id),
    tag VARCHAR(255)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    ordered_at DATE,
    payment_provider VARCHAR(255),
    payment_status VARCHAR(255),
    stripe_checkout_session_id VARCHAR(255),
    stripe_payment_intent_id VARCHAR(255),
    paid_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE order_items (
    order_id BIGINT NOT NULL REFERENCES orders(id),
    product_id VARCHAR(255) REFERENCES products(external_id),
    product_name VARCHAR(255),
    unit_price NUMERIC(19, 2),
    quantity INTEGER
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    product_id VARCHAR(255) NOT NULL REFERENCES products(external_id),
    quantity INTEGER,
    added_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE product_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255),
    product_id VARCHAR(255) REFERENCES products(external_id),
    reason VARCHAR(255),
    related_simulation_id VARCHAR(255),
    priority VARCHAR(255),
    dismissed BOOLEAN
);

CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255),
    discount VARCHAR(255),
    cost_coins INTEGER
);

CREATE TABLE emergency_kits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    level VARCHAR(255),
    image_url VARCHAR(255),
    description VARCHAR(2000),
    individual_price NUMERIC(19, 2),
    kit_price NUMERIC(19, 2),
    savings NUMERIC(19, 2),
    savings_percentage INTEGER,
    popular BOOLEAN
);

CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255),
    label VARCHAR(255),
    description VARCHAR(255),
    processing_fee NUMERIC(19, 2),
    available BOOLEAN
);

CREATE TABLE shipping_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255),
    label VARCHAR(255),
    recipient_name VARCHAR(255),
    phone VARCHAR(255),
    country VARCHAR(255),
    region VARCHAR(255),
    city VARCHAR(255),
    district VARCHAR(255),
    postal_code VARCHAR(255),
    street VARCHAR(255),
    street_number VARCHAR(255),
    reference VARCHAR(255),
    default_address BOOLEAN
);
-- Las columnas de usuario y otras referencias externas son lógicas.
